### ISSUE TITLE
Codigo de  ESP32

### ISSUE THREAD

**Issue by BonillaZLeonardo** [DrLAlbertoAngelesH/EstudioDelTrabajoII-2024-1#173]
Hola profesor, quería preguntarle si podría publicar el código que uso para el ESP 32 que ayer mismo modifico para poder usarla, gracias y disculpe las molestias

**Comment by LAAngeles** [comment]
// https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/api/i2c.html

#include <LiquidCrystal_I2C.h> //Libreria LCD_I2C
#include "Wire.h"

//Crear el objeto lcd  dirección  0x27 y 16 columnas x 2 filas
LiquidCrystal_I2C lcd(0x27,16,2); 

#define pot 0
int potenciometro;
int sdaPin = 6;
int sclPin = 7;
void setup() 
{
  // configuramos los pines de Serial data line y Serial clock line
  Wire.setPins(sdaPin,sclPin);
  // inicializamos la comunicacion como master
  Wire.begin();
  // iniciamos la comunicacion serial
  Serial.begin(115200);
  // Inicializar el LCD
  lcd.init();
  //Encender la luz de fondo.
  lcd.backlight();
  lcd.clear();
  // Ubicamos el cursor en la primera posición(columna:0) de la primera línea(fila:0)
  lcd.setCursor(0,0);
  // Escribimos el Mensaje en el LCD.
  lcd.print ("Potenciometro");
  //////////////////////////////
    //set the resolution to 12 bits (0-4096)
  analogReadResolution(12); 
  ////////////////////////////// 
}
 
void loop() 
{
   // Ubicamos el cursor en la primera posición(columna:0) de la segunda línea(fila:1)
  lcd.setCursor(0,1);
  potenciometro = analogRead(pot);
  // se borra la pantalla para evitar que se mantengan las centenas
  if(potenciometro<100 || potenciometro<1000){
      lcd.clear();
      lcd.setCursor(0,0);
      lcd.print ("Potenciometro");
      lcd.setCursor(0,1);
  }
  lcd.print(potenciometro);
  Serial.printf("Pot : %d \n\r",potenciometro);
  delay(1000);
}

**Comment by BonillaZLeonardo** [comment]
#include <Wire.h>
#include <LiquidCrystal_I2C.h>

LiquidCrystal_I2C LCD = LiquidCrystal_I2C(0x27, 16, 2);

#define potPin 0

void setup() {
  Serial.begin(115200);

  LCD.init();
  LCD.backlight();
  LCD.setCursor(0, 0);
  LCD.println("Potenciometro");
}

void loop() {
  int potValue = analogRead(potPin);

  LCD.setCursor(0, 1);
  LCD.print("               "); // Limpiar la línea antes de escribir el nuevo valor
  LCD.setCursor(0, 1);
  LCD.print(potValue);

  delay(250);
}

**Comment by BonillaZLeonardo** [comment]
#include <Wire.h>
#include <LiquidCrystal_I2C.h>

LiquidCrystal_I2C LCD = LiquidCrystal_I2C(0x27, 16, 2);

#define potPin 0

void setup() {
  Serial.begin(115200);

  LCD.init();
  LCD.backlight();
  LCD.setCursor(0, 0);
  LCD.println("Potenciometro");
}

void loop() {
  int potValue = analogRead(potPin);

  LCD.setCursor(0, 1);
  LCD.print("               "); // Limpiar la línea antes de escribir el nuevo valor
  LCD.setCursor(0, 1);
  LCD.print(potValue);

  delay(250);
}

**Comment by BonillaZLeonardo** [comment]
#include <Wire.h>
#include <LiquidCrystal_I2C.h>

LiquidCrystal_I2C LCD = LiquidCrystal_I2C(0x27, 16, 2);

#define potPin 0

void setup() {
  Serial.begin(115200);

  LCD.init();
  LCD.backlight();
  LCD.setCursor(0, 0);
  LCD.println("Potenciometro");
}

void loop() {
  int potValue = analogRead(potPin);

  LCD.setCursor(0, 1);
  LCD.print("               "); // Limpiar la línea antes de escribir el nuevo valor
  LCD.setCursor(0, 1);
  LCD.print(potValue);

  delay(250);
}

**Comment by BonillaZLeonardo** [comment]
Hola profe, le mando un código para la ESP 32

#include <Wire.h>
#include <LiquidCrystal_I2C.h>

LiquidCrystal_I2C LCD = LiquidCrystal_I2C(0x27, 16, 2);

#define potPin 0

void setup() {
  Serial.begin(115200);

  LCD.init();
  LCD.backlight();
  LCD.setCursor(0, 0);
  LCD.println("Potenciometro");
}

void loop() {
  int potValue = analogRead(potPin);

  LCD.setCursor(0, 1);
  LCD.print("               "); // Limpiar la línea antes de escribir el nuevo valor
  LCD.setCursor(0, 1);
  LCD.print(potValue);

  delay(250);
}

**Comment by LAAngeles** [comment]
ya pude programar su esp32 en la clase se las entrego
