### ISSUE TITLE
Buenas noches profesor 

### ISSUE THREAD

**Issue by BonillaZLeonardo** [DrLAlbertoAngelesH/EstudioDelTrabajoII-2024-1#176]
Buenas noches profesor, disculpe las molestias, pero quería preguntarle a que hora llega al tecnológico y donde lo puedo encontrar profe, nuevamente disculpe las molestias.

**Comment by LAAngeles** [comment]
Hola, por lo regular llego a las 2:30 y me puedes encontrar en las oficinas del departamento de ingeniería industrial
